services:
  dashboard:
    #build: .
    image: ghcr.io/ao-ba/spotify_nowplaying:latest
    container_name: dashboard
    ports:
      - "5000:5000"
    env_file: "./.env"
    volumes:
      - .:/app
    restart: always
